server:
  addr: localhost:9090
  auth:
    server-url: https://localhost/realms/todoapp
    insecure-client: true
    client-id: todo-app

login:
  insecure-client: true

client:
  addr: http://localhost:9090
  insecure-client: true
  auth:
    server-url: https://localhost/realms/todoapp
    insecure-client: true
    client-id: todo-app
